config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :platforms
  resources :games

  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :games

  has_attached_file :logo, styles: { :medium => "640x", :thumb => "200x" }
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :platform
  belongs_to :developer

  has_attached_file :cover, styles: { :medium => "640x", :thumb => "200x" }
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :games

  has_attached_file :image, styles: { :medium => "640x", :thumb => "200x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:show, :edit, :update, :destroy]

  # GET /developers
  # GET /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1
  # GET /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers
  # POST /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Developer was successfully created.' }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1
  # PATCH/PUT /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: 'Developer was successfully updated.' }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1
  # DELETE /developers/1.json
  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: 'Developer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def developer_params
      params.require(:developer).permit(:name, :description, :logo)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :price, :relase_date, :description, :rating, :cover, :platform_id, :developer_id)
    end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(platform_params)

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render :show, status: :created, location: @platform }
      else
        format.html { render :new }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1
  # PATCH/PUT /platforms/1.json
  def update
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { render :show, status: :ok, location: @platform }
      else
        format.html { render :edit }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform.destroy
    respond_to do |format|
      format.html { redirect_to platforms_url, notice: 'Platform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_params
      params.require(:platform).permit(:name, :description, :vendor, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/developers/_form.html.erb
<%= form_with(model: developer, local: true) do |form| %>
  <% if developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing Developer</h1>

<%= render 'form', developer: @developer %>

<%= link_to 'Show', @developer %> |
<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Developers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.name %></td>
        <td><%= developer.description %></td>
        <td><%= image_tag developer.logo.url(:thumb) %></td>
        <td><%= link_to 'Show', developer %></td>
        <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
        <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Developer', new_developer_path %>

app/views/developers/new.html.erb
<h1>New Developer</h1>

<%= render 'form', developer: @developer %>

<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @developer.logo.url(:thumb) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @developer.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @developer.description %>
</p>

<p>
  <strong>Games:</strong>
  <ul>
    <% @developer.games.each do |game| %>
      <li><%= game.title %> <%= link_to "Details", game_path(game) %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_developer_path(@developer) %> |
<%= link_to 'Back', developers_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :relase_date %>
    <%= form.date_select :relase_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.collection_select(:platform_id, Platform.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :developer %>
    <%= form.collection_select(:developer_id, Developer.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Relase date</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Platform</th>
      <th>Developer</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.price %></td>
        <td><%= game.relase_date %></td>
        <td><%= game.description %></td>
        <td><%= game.rating %></td>
        <td><%= link_to game.platform.name, platform_path(game.platform) %></td>
        <td><%= link_to game.developer.name, developer_path(game.developer) %></td>
        <td><%= image_tag game.cover.url(:thumb) %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @game.cover.url(:thumb) %>
</p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>

<p>
  <strong>Relase date:</strong>
  <%= @game.relase_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @game.rating %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @game.platform.name %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @game.developer.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameBudget</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/platforms/_form.html.erb
<%= form_with(model: platform, local: true) do |form| %>
  <% if platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% platform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<h1>Editing Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Platforms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Vendor</th>
      <th>Thumb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @platforms.each do |platform| %>
      <tr>
        <td><%= platform.name %></td>
        <td><%= platform.description %></td>
        <td><%= platform.vendor %></td>
        <td><%= image_tag platform.image.url(:thumb) %></td>
        <td><%= link_to 'Show', platform %></td>
        <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
        <td><%= link_to 'Destroy', platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Platform', new_platform_path %>

app/views/platforms/new.html.erb
<h1>New Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Image:</strong>
  <%= image_tag @platform.image.url(:thumb) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @platform.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @platform.description %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @platform.vendor %>
</p>

<p>
  <strong>Games:</strong>
  <ul>
    <% @platform.games.each do |game| %>
      <li><%= game.title %> <%= link_to "Details", game_path(game) %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>